context.modules = [
    {
        name = libpipewire-module-combine-stream
        args = {
            combine.mode = sink
            node.name = "combined_displays"
            node.description = "All Displays (Samsung & Sony TV)"
            combine.latency-compensate = false
            combine.props = {
                audio.position = [ FL FR ]
            }
            stream.rules = [
                {
                    matches = [
                        { "node.name" = "alsa_output.pci-0000_01_00.1.pro-output-3" }
                    ]
                    actions = {
                        create-stream = {
                            audio.position = [ AUX0 AUX1 ]
                            target.object = "alsa_output.pci-0000_01_00.1.pro-output-3"
                        }
                    }
                },
                {
                    matches = [
                        { "node.name" = "alsa_output.pci-0000_01_00.1.pro-output-7" }
                    ]
                    actions = {
                        create-stream = {
                            audio.position = [ AUX0 AUX1 ]
                            target.object = "alsa_output.pci-0000_01_00.1.pro-output-7"
                        }
                    }
                }
            ]
        }
    }
]
