monitor.alsa.rules = [
  {
    matches = [
      {
        "node.name" = "~alsa_output.pci-0000_01_00.1.*"
      }
    ]
    actions = {
      update-props = {
        "priority.session" = 2000
        "priority.driver" = 2000
        "session.suspend-timeout-seconds" = 0
      }
    }
  },
  {
    matches = [
      {
        "device.name" = "alsa_card.pci-0000_00_1b.0"
      }
    ]
    actions = {
      update-props = {
        "device.disabled" = true
      }
    }
  },
  {
    matches = [
      {
        "device.name" = "alsa_card.pci-0000_00_03.0"
      }
    ]
    actions = {
      update-props = {
        "device.disabled" = true
      }
    }
  },
  {
    matches = [
      {
        "node.name" = "~alsa_output.usb-KTMICRO_FDUCE_M160.*"
      }
    ]
    actions = {
      update-props = {
        "node.disabled" = true
      }
    }
  }
]
